!function(){var o={"./source/scripts/consts.js":
/*!**********************************!*\
  !*** ./source/scripts/consts.js ***!
  \**********************************/function(e,n,o){"use strict";o.r(n),o.d(n,{PROJECTS_COLORED_ITEM_CLASS:function(){return j},PROJECTS_ITEM_CLASS:function(){return d},SLIDER_ACTIVE_BUTTON_CLASS:function(){return i},SLIDER_ACTIVE_SLIDE_LEFT:function(){return c},SLIDER_ACTIVE_SLIDE_RIGHT:function(){return l},SLIDER_DATA_ATTRIBUTE:function(){return t},SLIDER_HIDDEN_SLIDE_LEFT:function(){return u},SLIDER_HIDDEN_SLIDE_RIGHT:function(){return a},SWIP_DIRRECTION:function(){return s},TABLET_WIDHT:function(){return r},TEAM_COLORED_ITEM_CLASS:function(){return m},TEAM_ITEM_CLASS:function(){return f}});var r=900,s={RIGHT:"right",LEFT:"left"},t="data-slide-name",i="project-slider__thumbnails-button--active",c="project-slider__slide--active--left",l="project-slider__slide--active--right",u="project-slider__slide--hidden--left",a="project-slider__slide--hidden--right",d=".projects__card",j="projects__card--colored",f=".our-team__item",m="our-team__item--colored"},"./node_modules/core-js/internals/a-callable.js":
/*!******************************************************!*\
  !*** ./node_modules/core-js/internals/a-callable.js ***!
  \******************************************************/function(e,n,o){var r=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),s=o(/*! ../internals/try-to-string */"./node_modules/core-js/internals/try-to-string.js"),t=TypeError;e.exports=function(e){if(r(e))return e;throw t(s(e)+" is not a function")}},"./node_modules/core-js/internals/a-possible-prototype.js":
/*!****************************************************************!*\
  !*** ./node_modules/core-js/internals/a-possible-prototype.js ***!
  \****************************************************************/function(e,n,o){var r=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),s=String,t=TypeError;e.exports=function(e){if("object"==typeof e||r(e))return e;throw t("Can't set "+s(e)+" as a prototype")}},"./node_modules/core-js/internals/an-object.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/an-object.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),s=String,t=TypeError;e.exports=function(e){if(r(e))return e;throw t(s(e)+" is not an object")}},"./node_modules/core-js/internals/array-for-each.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/array-for-each.js ***!
  \**********************************************************/function(e,n,o){"use strict";var r=o(/*! ../internals/array-iteration */"./node_modules/core-js/internals/array-iteration.js").forEach,o=o(/*! ../internals/array-method-is-strict */"./node_modules/core-js/internals/array-method-is-strict.js")("forEach");e.exports=o?[].forEach:function(e){return r(this,e,1<arguments.length?arguments[1]:void 0)}},"./node_modules/core-js/internals/array-includes.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/array-includes.js ***!
  \**********************************************************/function(e,n,o){function r(c){return function(e,n,o){var r,s=l(e),t=a(s),i=u(o,t);if(c&&n!=n){for(;i<t;)if((r=s[i++])!=r)return!0}else for(;i<t;i++)if((c||i in s)&&s[i]===n)return c||i||0;return!c&&-1}}var l=o(/*! ../internals/to-indexed-object */"./node_modules/core-js/internals/to-indexed-object.js"),u=o(/*! ../internals/to-absolute-index */"./node_modules/core-js/internals/to-absolute-index.js"),a=o(/*! ../internals/length-of-array-like */"./node_modules/core-js/internals/length-of-array-like.js");e.exports={includes:r(!0),indexOf:r(!1)}},"./node_modules/core-js/internals/array-iteration.js":
/*!***********************************************************!*\
  !*** ./node_modules/core-js/internals/array-iteration.js ***!
  \***********************************************************/function(e,n,o){function r(j){var f=1==j,m=2==j,_=3==j,p=4==j,b=6==j,y=7==j,h=5==j||b;return function(e,n,o,r){for(var s,t,i=S(e),c=g(i),l=v(n,o),u=E(c),a=0,n=r||T,d=f?n(e,u):m||y?n(e,0):void 0;a<u;a++)if((h||a in c)&&(t=l(s=c[a],a,i),j))if(f)d[a]=t;else if(t)switch(j){case 3:return!0;case 5:return s;case 6:return a;case 2:I(d,s)}else switch(j){case 4:return!1;case 7:I(d,s)}return b?-1:_||p?p:d}}var v=o(/*! ../internals/function-bind-context */"./node_modules/core-js/internals/function-bind-context.js"),s=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),g=o(/*! ../internals/indexed-object */"./node_modules/core-js/internals/indexed-object.js"),S=o(/*! ../internals/to-object */"./node_modules/core-js/internals/to-object.js"),E=o(/*! ../internals/length-of-array-like */"./node_modules/core-js/internals/length-of-array-like.js"),T=o(/*! ../internals/array-species-create */"./node_modules/core-js/internals/array-species-create.js"),I=s([].push);e.exports={forEach:r(0),map:r(1),filter:r(2),some:r(3),every:r(4),find:r(5),findIndex:r(6),filterReject:r(7)}},"./node_modules/core-js/internals/array-method-is-strict.js":
/*!******************************************************************!*\
  !*** ./node_modules/core-js/internals/array-method-is-strict.js ***!
  \******************************************************************/function(e,n,o){"use strict";var r=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js");e.exports=function(e,n){var o=[][e];return!!o&&r(function(){o.call(null,n||function(){return 1},1)})}},"./node_modules/core-js/internals/array-species-constructor.js":
/*!*********************************************************************!*\
  !*** ./node_modules/core-js/internals/array-species-constructor.js ***!
  \*********************************************************************/function(e,n,o){var r=o(/*! ../internals/is-array */"./node_modules/core-js/internals/is-array.js"),s=o(/*! ../internals/is-constructor */"./node_modules/core-js/internals/is-constructor.js"),t=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),i=o(/*! ../internals/well-known-symbol */"./node_modules/core-js/internals/well-known-symbol.js")("species"),c=Array;e.exports=function(e){var n;return r(e)&&(n=e.constructor,(s(n)&&(n===c||r(n.prototype))||t(n)&&null===(n=n[i]))&&(n=void 0)),void 0===n?c:n}},"./node_modules/core-js/internals/array-species-create.js":
/*!****************************************************************!*\
  !*** ./node_modules/core-js/internals/array-species-create.js ***!
  \****************************************************************/function(e,n,o){var r=o(/*! ../internals/array-species-constructor */"./node_modules/core-js/internals/array-species-constructor.js");e.exports=function(e,n){return new(r(e))(0===n?0:n)}},"./node_modules/core-js/internals/classof-raw.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/classof-raw.js ***!
  \*******************************************************/function(e,n,o){var o=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),r=o({}.toString),s=o("".slice);e.exports=function(e){return s(r(e),8,-1)}},"./node_modules/core-js/internals/classof.js":
/*!***************************************************!*\
  !*** ./node_modules/core-js/internals/classof.js ***!
  \***************************************************/function(e,n,o){var r=o(/*! ../internals/to-string-tag-support */"./node_modules/core-js/internals/to-string-tag-support.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),t=o(/*! ../internals/classof-raw */"./node_modules/core-js/internals/classof-raw.js"),i=o(/*! ../internals/well-known-symbol */"./node_modules/core-js/internals/well-known-symbol.js")("toStringTag"),c=Object,l="Arguments"==t(function(){return arguments}());e.exports=r?t:function(e){var n;return void 0===e?"Undefined":null===e?"Null":"string"==typeof(n=function(e,n){try{return e[n]}catch(e){}}(e=c(e),i))?n:l?t(e):"Object"==(n=t(e))&&s(e.callee)?"Arguments":n}},"./node_modules/core-js/internals/copy-constructor-properties.js":
/*!***********************************************************************!*\
  !*** ./node_modules/core-js/internals/copy-constructor-properties.js ***!
  \***********************************************************************/function(e,n,o){var l=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),u=o(/*! ../internals/own-keys */"./node_modules/core-js/internals/own-keys.js"),a=o(/*! ../internals/object-get-own-property-descriptor */"./node_modules/core-js/internals/object-get-own-property-descriptor.js"),d=o(/*! ../internals/object-define-property */"./node_modules/core-js/internals/object-define-property.js");e.exports=function(e,n,o){for(var r=u(n),s=d.f,t=a.f,i=0;i<r.length;i++){var c=r[i];l(e,c)||o&&l(o,c)||s(e,c,t(n,c))}}},"./node_modules/core-js/internals/create-non-enumerable-property.js":
/*!**************************************************************************!*\
  !*** ./node_modules/core-js/internals/create-non-enumerable-property.js ***!
  \**************************************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),s=o(/*! ../internals/object-define-property */"./node_modules/core-js/internals/object-define-property.js"),t=o(/*! ../internals/create-property-descriptor */"./node_modules/core-js/internals/create-property-descriptor.js");e.exports=r?function(e,n,o){return s.f(e,n,t(1,o))}:function(e,n,o){return e[n]=o,e}},"./node_modules/core-js/internals/create-property-descriptor.js":
/*!**********************************************************************!*\
  !*** ./node_modules/core-js/internals/create-property-descriptor.js ***!
  \**********************************************************************/function(e){e.exports=function(e,n){return{enumerable:!(1&e),configurable:!(2&e),writable:!(4&e),value:n}}},"./node_modules/core-js/internals/define-built-in.js":
/*!***********************************************************!*\
  !*** ./node_modules/core-js/internals/define-built-in.js ***!
  \***********************************************************/function(e,n,o){var i=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),c=o(/*! ../internals/object-define-property */"./node_modules/core-js/internals/object-define-property.js"),l=o(/*! ../internals/make-built-in */"./node_modules/core-js/internals/make-built-in.js"),u=o(/*! ../internals/define-global-property */"./node_modules/core-js/internals/define-global-property.js");e.exports=function(e,n,o,r){var s=(r=r||{}).enumerable,t=void 0!==r.name?r.name:n;if(i(o)&&l(o,t,r),r.global)s?e[n]=o:u(n,o);else{try{r.unsafe?e[n]&&(s=!0):delete e[n]}catch(e){}s?e[n]=o:c.f(e,n,{value:o,enumerable:!1,configurable:!r.nonConfigurable,writable:!r.nonWritable})}return e}},"./node_modules/core-js/internals/define-global-property.js":
/*!******************************************************************!*\
  !*** ./node_modules/core-js/internals/define-global-property.js ***!
  \******************************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),s=Object.defineProperty;e.exports=function(n,o){try{s(r,n,{value:o,configurable:!0,writable:!0})}catch(e){r[n]=o}return o}},"./node_modules/core-js/internals/descriptors.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/descriptors.js ***!
  \*******************************************************/function(e,n,o){o=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js");e.exports=!o(function(){return 7!=Object.defineProperty({},1,{get:function(){return 7}})[1]})},"./node_modules/core-js/internals/document-create-element.js":
/*!*******************************************************************!*\
  !*** ./node_modules/core-js/internals/document-create-element.js ***!
  \*******************************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),o=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),s=r.document,t=o(s)&&o(s.createElement);e.exports=function(e){return t?s.createElement(e):{}}},"./node_modules/core-js/internals/dom-iterables.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/dom-iterables.js ***!
  \*********************************************************/function(e){e.exports={CSSRuleList:0,CSSStyleDeclaration:0,CSSValueList:0,ClientRectList:0,DOMRectList:0,DOMStringList:0,DOMTokenList:1,DataTransferItemList:0,FileList:0,HTMLAllCollection:0,HTMLCollection:0,HTMLFormElement:0,HTMLSelectElement:0,MediaList:0,MimeTypeArray:0,NamedNodeMap:0,NodeList:1,PaintRequestList:0,Plugin:0,PluginArray:0,SVGLengthList:0,SVGNumberList:0,SVGPathSegList:0,SVGPointList:0,SVGStringList:0,SVGTransformList:0,SourceBufferList:0,StyleSheetList:0,TextTrackCueList:0,TextTrackList:0,TouchList:0}},"./node_modules/core-js/internals/dom-token-list-prototype.js":
/*!********************************************************************!*\
  !*** ./node_modules/core-js/internals/dom-token-list-prototype.js ***!
  \********************************************************************/function(e,n,o){o=o(/*! ../internals/document-create-element */"./node_modules/core-js/internals/document-create-element.js")("span").classList,o=o&&o.constructor&&o.constructor.prototype;e.exports=o===Object.prototype?void 0:o},"./node_modules/core-js/internals/engine-user-agent.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/engine-user-agent.js ***!
  \*************************************************************/function(e,n,o){o=o(/*! ../internals/get-built-in */"./node_modules/core-js/internals/get-built-in.js");e.exports=o("navigator","userAgent")||""},"./node_modules/core-js/internals/engine-v8-version.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/engine-v8-version.js ***!
  \*************************************************************/function(e,n,o){var r,s,t=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),o=o(/*! ../internals/engine-user-agent */"./node_modules/core-js/internals/engine-user-agent.js"),i=t.process,t=t.Deno,i=i&&i.versions||t&&t.version,t=i&&i.v8;!(s=t?0<(r=t.split("."))[0]&&r[0]<4?1:+(r[0]+r[1]):s)&&o&&(!(r=o.match(/Edge\/(\d+)/))||74<=r[1])&&(r=o.match(/Chrome\/(\d+)/))&&(s=+r[1]),e.exports=s},"./node_modules/core-js/internals/enum-bug-keys.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/enum-bug-keys.js ***!
  \*********************************************************/function(e){e.exports=["constructor","hasOwnProperty","isPrototypeOf","propertyIsEnumerable","toLocaleString","toString","valueOf"]},"./node_modules/core-js/internals/export.js":
/*!**************************************************!*\
  !*** ./node_modules/core-js/internals/export.js ***!
  \**************************************************/function(e,n,o){var u=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),a=o(/*! ../internals/object-get-own-property-descriptor */"./node_modules/core-js/internals/object-get-own-property-descriptor.js").f,d=o(/*! ../internals/create-non-enumerable-property */"./node_modules/core-js/internals/create-non-enumerable-property.js"),j=o(/*! ../internals/define-built-in */"./node_modules/core-js/internals/define-built-in.js"),f=o(/*! ../internals/define-global-property */"./node_modules/core-js/internals/define-global-property.js"),m=o(/*! ../internals/copy-constructor-properties */"./node_modules/core-js/internals/copy-constructor-properties.js"),_=o(/*! ../internals/is-forced */"./node_modules/core-js/internals/is-forced.js");e.exports=function(e,n){var o,r,s,t=e.target,i=e.global,c=e.stat,l=i?u:c?u[t]||f(t,{}):(u[t]||{}).prototype;if(l)for(o in n){if(r=n[o],s=e.dontCallGetSet?(s=a(l,o))&&s.value:l[o],!_(i?o:t+(c?".":"#")+o,e.forced)&&void 0!==s){if(typeof r==typeof s)continue;m(r,s)}(e.sham||s&&s.sham)&&d(r,"sham",!0),j(l,o,r,e)}}},"./node_modules/core-js/internals/fails.js":
/*!*************************************************!*\
  !*** ./node_modules/core-js/internals/fails.js ***!
  \*************************************************/function(e){e.exports=function(e){try{return!!e()}catch(e){return!0}}},"./node_modules/core-js/internals/function-bind-context.js":
/*!*****************************************************************!*\
  !*** ./node_modules/core-js/internals/function-bind-context.js ***!
  \*****************************************************************/function(e,n,o){var r=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),s=o(/*! ../internals/a-callable */"./node_modules/core-js/internals/a-callable.js"),t=o(/*! ../internals/function-bind-native */"./node_modules/core-js/internals/function-bind-native.js"),i=r(r.bind);e.exports=function(e,n){return s(e),void 0===n?e:t?i(e,n):function(){return e.apply(n,arguments)}}},"./node_modules/core-js/internals/function-bind-native.js":
/*!****************************************************************!*\
  !*** ./node_modules/core-js/internals/function-bind-native.js ***!
  \****************************************************************/function(e,n,o){o=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js");e.exports=!o(function(){var e=function(){}.bind();return"function"!=typeof e||e.hasOwnProperty("prototype")})},"./node_modules/core-js/internals/function-call.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/function-call.js ***!
  \*********************************************************/function(e,n,o){var o=o(/*! ../internals/function-bind-native */"./node_modules/core-js/internals/function-bind-native.js"),r=Function.prototype.call;e.exports=o?r.bind(r):function(){return r.apply(r,arguments)}},"./node_modules/core-js/internals/function-name.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/function-name.js ***!
  \*********************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),o=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),s=Function.prototype,t=r&&Object.getOwnPropertyDescriptor,o=o(s,"name"),i=o&&"something"===function(){}.name,r=o&&(!r||t(s,"name").configurable);e.exports={EXISTS:o,PROPER:i,CONFIGURABLE:r}},"./node_modules/core-js/internals/function-uncurry-this.js":
/*!*****************************************************************!*\
  !*** ./node_modules/core-js/internals/function-uncurry-this.js ***!
  \*****************************************************************/function(e,n,o){var o=o(/*! ../internals/function-bind-native */"./node_modules/core-js/internals/function-bind-native.js"),r=Function.prototype,s=r.bind,t=r.call,i=o&&s.bind(t,t);e.exports=o?function(e){return e&&i(e)}:function(e){return e&&function(){return t.apply(e,arguments)}}},"./node_modules/core-js/internals/get-built-in.js":
/*!********************************************************!*\
  !*** ./node_modules/core-js/internals/get-built-in.js ***!
  \********************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js");e.exports=function(e,n){return arguments.length<2?(o=r[e],s(o)?o:void 0):r[e]&&r[e][n];var o}},"./node_modules/core-js/internals/get-method.js":
/*!******************************************************!*\
  !*** ./node_modules/core-js/internals/get-method.js ***!
  \******************************************************/function(e,n,o){var r=o(/*! ../internals/a-callable */"./node_modules/core-js/internals/a-callable.js");e.exports=function(e,n){e=e[n];return null==e?void 0:r(e)}},"./node_modules/core-js/internals/global.js":
/*!**************************************************!*\
  !*** ./node_modules/core-js/internals/global.js ***!
  \**************************************************/function(e,n,o){function r(e){return e&&e.Math==Math&&e}e.exports=r("object"==typeof globalThis&&globalThis)||r("object"==typeof window&&window)||r("object"==typeof self&&self)||r("object"==typeof o.g&&o.g)||function(){return this}()||Function("return this")()},"./node_modules/core-js/internals/has-own-property.js":
/*!************************************************************!*\
  !*** ./node_modules/core-js/internals/has-own-property.js ***!
  \************************************************************/function(e,n,o){var r=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),s=o(/*! ../internals/to-object */"./node_modules/core-js/internals/to-object.js"),t=r({}.hasOwnProperty);e.exports=Object.hasOwn||function(e,n){return t(s(e),n)}},"./node_modules/core-js/internals/hidden-keys.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/hidden-keys.js ***!
  \*******************************************************/function(e){e.exports={}},"./node_modules/core-js/internals/ie8-dom-define.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/ie8-dom-define.js ***!
  \**********************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),s=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),t=o(/*! ../internals/document-create-element */"./node_modules/core-js/internals/document-create-element.js");e.exports=!r&&!s(function(){return 7!=Object.defineProperty(t("div"),"a",{get:function(){return 7}}).a})},"./node_modules/core-js/internals/indexed-object.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/indexed-object.js ***!
  \**********************************************************/function(e,n,o){var r=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),s=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),t=o(/*! ../internals/classof-raw */"./node_modules/core-js/internals/classof-raw.js"),i=Object,c=r("".split);e.exports=s(function(){return!i("z").propertyIsEnumerable(0)})?function(e){return"String"==t(e)?c(e,""):i(e)}:i},"./node_modules/core-js/internals/inherit-if-required.js":
/*!***************************************************************!*\
  !*** ./node_modules/core-js/internals/inherit-if-required.js ***!
  \***************************************************************/function(e,n,o){var r=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),s=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),t=o(/*! ../internals/object-set-prototype-of */"./node_modules/core-js/internals/object-set-prototype-of.js");e.exports=function(e,n,o){return t&&r(n=n.constructor)&&n!==o&&s(n=n.prototype)&&n!==o.prototype&&t(e,n),e}},"./node_modules/core-js/internals/inspect-source.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/inspect-source.js ***!
  \**********************************************************/function(e,n,o){var r=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),o=o(/*! ../internals/shared-store */"./node_modules/core-js/internals/shared-store.js"),t=r(Function.toString);s(o.inspectSource)||(o.inspectSource=function(e){return t(e)}),e.exports=o.inspectSource},"./node_modules/core-js/internals/internal-state.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/internal-state.js ***!
  \**********************************************************/function(e,n,o){var r,s,t,i,c,l,u,a,d=o(/*! ../internals/native-weak-map */"./node_modules/core-js/internals/native-weak-map.js"),j=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),f=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),m=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),_=o(/*! ../internals/create-non-enumerable-property */"./node_modules/core-js/internals/create-non-enumerable-property.js"),p=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),b=o(/*! ../internals/shared-store */"./node_modules/core-js/internals/shared-store.js"),y=o(/*! ../internals/shared-key */"./node_modules/core-js/internals/shared-key.js"),o=o(/*! ../internals/hidden-keys */"./node_modules/core-js/internals/hidden-keys.js"),h="Object already initialized",v=j.TypeError,j=j.WeakMap;u=d||b.state?(r=b.state||(b.state=new j),s=f(r.get),t=f(r.has),i=f(r.set),c=function(e,n){if(t(r,e))throw new v(h);return n.facade=e,i(r,e,n),n},l=function(e){return s(r,e)||{}},function(e){return t(r,e)}):(o[a=y("state")]=!0,c=function(e,n){if(p(e,a))throw new v(h);return n.facade=e,_(e,a,n),n},l=function(e){return p(e,a)?e[a]:{}},function(e){return p(e,a)}),e.exports={set:c,get:l,has:u,enforce:function(e){return u(e)?l(e):c(e,{})},getterFor:function(n){return function(e){if(m(e)&&(e=l(e)).type===n)return e;throw v("Incompatible receiver, "+n+" required")}}}},"./node_modules/core-js/internals/is-array.js":
/*!****************************************************!*\
  !*** ./node_modules/core-js/internals/is-array.js ***!
  \****************************************************/function(e,n,o){var r=o(/*! ../internals/classof-raw */"./node_modules/core-js/internals/classof-raw.js");e.exports=Array.isArray||function(e){return"Array"==r(e)}},"./node_modules/core-js/internals/is-callable.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/is-callable.js ***!
  \*******************************************************/function(e){e.exports=function(e){return"function"==typeof e}},"./node_modules/core-js/internals/is-constructor.js":
/*!**********************************************************!*\
  !*** ./node_modules/core-js/internals/is-constructor.js ***!
  \**********************************************************/function(e,n,o){function r(){}function s(e){if(!l(e))return!1;try{return f(r,j,e),!0}catch(e){return!1}}function t(e){if(!l(e))return!1;switch(u(e)){case"AsyncFunction":case"GeneratorFunction":case"AsyncGeneratorFunction":return!1}try{return p||!!_(m,d(e))}catch(e){return!0}}var i=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),c=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),l=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),u=o(/*! ../internals/classof */"./node_modules/core-js/internals/classof.js"),a=o(/*! ../internals/get-built-in */"./node_modules/core-js/internals/get-built-in.js"),d=o(/*! ../internals/inspect-source */"./node_modules/core-js/internals/inspect-source.js"),j=[],f=a("Reflect","construct"),m=/^\s*(?:class|function)\b/,_=i(m.exec),p=!m.exec(r);t.sham=!0,e.exports=!f||c(function(){var e;return s(s.call)||!s(Object)||!s(function(){e=!0})||e})?t:s},"./node_modules/core-js/internals/is-forced.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/is-forced.js ***!
  \*****************************************************/function(e,n,o){function r(e,n){return(e=l[c(e)])==a||e!=u&&(t(n)?s(n):!!n)}var s=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),t=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),i=/#|\.prototype\./,c=r.normalize=function(e){return String(e).replace(i,".").toLowerCase()},l=r.data={},u=r.NATIVE="N",a=r.POLYFILL="P";e.exports=r},"./node_modules/core-js/internals/is-object.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/is-object.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js");e.exports=function(e){return"object"==typeof e?null!==e:r(e)}},"./node_modules/core-js/internals/is-pure.js":
/*!***************************************************!*\
  !*** ./node_modules/core-js/internals/is-pure.js ***!
  \***************************************************/function(e){e.exports=!1},"./node_modules/core-js/internals/is-symbol.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/is-symbol.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/get-built-in */"./node_modules/core-js/internals/get-built-in.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),t=o(/*! ../internals/object-is-prototype-of */"./node_modules/core-js/internals/object-is-prototype-of.js"),o=o(/*! ../internals/use-symbol-as-uid */"./node_modules/core-js/internals/use-symbol-as-uid.js"),i=Object;e.exports=o?function(e){return"symbol"==typeof e}:function(e){var n=r("Symbol");return s(n)&&t(n.prototype,i(e))}},"./node_modules/core-js/internals/length-of-array-like.js":
/*!****************************************************************!*\
  !*** ./node_modules/core-js/internals/length-of-array-like.js ***!
  \****************************************************************/function(e,n,o){var r=o(/*! ../internals/to-length */"./node_modules/core-js/internals/to-length.js");e.exports=function(e){return r(e.length)}},"./node_modules/core-js/internals/make-built-in.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/make-built-in.js ***!
  \*********************************************************/function(e,n,o){var r=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),t=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),i=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),c=o(/*! ../internals/function-name */"./node_modules/core-js/internals/function-name.js").CONFIGURABLE,l=o(/*! ../internals/inspect-source */"./node_modules/core-js/internals/inspect-source.js"),o=o(/*! ../internals/internal-state */"./node_modules/core-js/internals/internal-state.js"),u=o.enforce,a=o.get,d=Object.defineProperty,j=i&&!r(function(){return 8!==d(function(){},"length",{value:8}).length}),f=String(String).split("String"),o=e.exports=function(e,n,o){"Symbol("===String(n).slice(0,7)&&(n="["+String(n).replace(/^Symbol\(([^)]*)\)/,"$1")+"]"),o&&o.getter&&(n="get "+n),o&&o.setter&&(n="set "+n),(!t(e,"name")||c&&e.name!==n)&&(i?d(e,"name",{value:n,configurable:!0}):e.name=n),j&&o&&t(o,"arity")&&e.length!==o.arity&&d(e,"length",{value:o.arity});try{o&&t(o,"constructor")&&o.constructor?i&&d(e,"prototype",{writable:!1}):e.prototype&&(e.prototype=void 0)}catch(e){}o=u(e);return t(o,"source")||(o.source=f.join("string"==typeof n?n:"")),e};Function.prototype.toString=o(function(){return s(this)&&a(this).source||l(this)},"toString")},"./node_modules/core-js/internals/math-trunc.js":
/*!******************************************************!*\
  !*** ./node_modules/core-js/internals/math-trunc.js ***!
  \******************************************************/function(e){var n=Math.ceil,o=Math.floor;e.exports=Math.trunc||function(e){e=+e;return(0<e?o:n)(e)}},"./node_modules/core-js/internals/native-symbol.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/native-symbol.js ***!
  \*********************************************************/function(e,n,o){var r=o(/*! ../internals/engine-v8-version */"./node_modules/core-js/internals/engine-v8-version.js"),o=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js");e.exports=!!Object.getOwnPropertySymbols&&!o(function(){var e=Symbol();return!String(e)||!(Object(e)instanceof Symbol)||!Symbol.sham&&r&&r<41})},"./node_modules/core-js/internals/native-weak-map.js":
/*!***********************************************************!*\
  !*** ./node_modules/core-js/internals/native-weak-map.js ***!
  \***********************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),s=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),o=o(/*! ../internals/inspect-source */"./node_modules/core-js/internals/inspect-source.js"),r=r.WeakMap;e.exports=s(r)&&/native code/.test(o(r))},"./node_modules/core-js/internals/object-define-property.js":
/*!******************************************************************!*\
  !*** ./node_modules/core-js/internals/object-define-property.js ***!
  \******************************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),s=o(/*! ../internals/ie8-dom-define */"./node_modules/core-js/internals/ie8-dom-define.js"),t=o(/*! ../internals/v8-prototype-define-bug */"./node_modules/core-js/internals/v8-prototype-define-bug.js"),i=o(/*! ../internals/an-object */"./node_modules/core-js/internals/an-object.js"),c=o(/*! ../internals/to-property-key */"./node_modules/core-js/internals/to-property-key.js"),l=TypeError,u=Object.defineProperty,a=Object.getOwnPropertyDescriptor,d="enumerable",j="configurable",f="writable";n.f=r?t?function(e,n,o){var r;return i(e),n=c(n),i(o),"function"==typeof e&&"prototype"===n&&"value"in o&&f in o&&!o[f]&&((r=a(e,n))&&r[f]&&(e[n]=o.value,o={configurable:(j in o?o:r)[j],enumerable:(d in o?o:r)[d],writable:!1})),u(e,n,o)}:u:function(e,n,o){if(i(e),n=c(n),i(o),s)try{return u(e,n,o)}catch(e){}if("get"in o||"set"in o)throw l("Accessors not supported");return"value"in o&&(e[n]=o.value),e}},"./node_modules/core-js/internals/object-get-own-property-descriptor.js":
/*!******************************************************************************!*\
  !*** ./node_modules/core-js/internals/object-get-own-property-descriptor.js ***!
  \******************************************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),s=o(/*! ../internals/function-call */"./node_modules/core-js/internals/function-call.js"),t=o(/*! ../internals/object-property-is-enumerable */"./node_modules/core-js/internals/object-property-is-enumerable.js"),i=o(/*! ../internals/create-property-descriptor */"./node_modules/core-js/internals/create-property-descriptor.js"),c=o(/*! ../internals/to-indexed-object */"./node_modules/core-js/internals/to-indexed-object.js"),l=o(/*! ../internals/to-property-key */"./node_modules/core-js/internals/to-property-key.js"),u=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),a=o(/*! ../internals/ie8-dom-define */"./node_modules/core-js/internals/ie8-dom-define.js"),d=Object.getOwnPropertyDescriptor;n.f=r?d:function(e,n){if(e=c(e),n=l(n),a)try{return d(e,n)}catch(e){}if(u(e,n))return i(!s(t.f,e,n),e[n])}},"./node_modules/core-js/internals/object-get-own-property-names.js":
/*!*************************************************************************!*\
  !*** ./node_modules/core-js/internals/object-get-own-property-names.js ***!
  \*************************************************************************/function(e,n,o){var r=o(/*! ../internals/object-keys-internal */"./node_modules/core-js/internals/object-keys-internal.js"),s=o(/*! ../internals/enum-bug-keys */"./node_modules/core-js/internals/enum-bug-keys.js").concat("length","prototype");n.f=Object.getOwnPropertyNames||function(e){return r(e,s)}},"./node_modules/core-js/internals/object-get-own-property-symbols.js":
/*!***************************************************************************!*\
  !*** ./node_modules/core-js/internals/object-get-own-property-symbols.js ***!
  \***************************************************************************/function(e,n){n.f=Object.getOwnPropertySymbols},"./node_modules/core-js/internals/object-is-prototype-of.js":
/*!******************************************************************!*\
  !*** ./node_modules/core-js/internals/object-is-prototype-of.js ***!
  \******************************************************************/function(e,n,o){o=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js");e.exports=o({}.isPrototypeOf)},"./node_modules/core-js/internals/object-keys-internal.js":
/*!****************************************************************!*\
  !*** ./node_modules/core-js/internals/object-keys-internal.js ***!
  \****************************************************************/function(e,n,o){var r=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),i=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),c=o(/*! ../internals/to-indexed-object */"./node_modules/core-js/internals/to-indexed-object.js"),l=o(/*! ../internals/array-includes */"./node_modules/core-js/internals/array-includes.js").indexOf,u=o(/*! ../internals/hidden-keys */"./node_modules/core-js/internals/hidden-keys.js"),a=r([].push);e.exports=function(e,n){var o,r=c(e),s=0,t=[];for(o in r)!i(u,o)&&i(r,o)&&a(t,o);for(;n.length>s;)!i(r,o=n[s++])||~l(t,o)||a(t,o);return t}},"./node_modules/core-js/internals/object-property-is-enumerable.js":
/*!*************************************************************************!*\
  !*** ./node_modules/core-js/internals/object-property-is-enumerable.js ***!
  \*************************************************************************/function(e,n){"use strict";var o={}.propertyIsEnumerable,r=Object.getOwnPropertyDescriptor,s=r&&!o.call({1:2},1);n.f=s?function(e){e=r(this,e);return!!e&&e.enumerable}:o},"./node_modules/core-js/internals/object-set-prototype-of.js":
/*!*******************************************************************!*\
  !*** ./node_modules/core-js/internals/object-set-prototype-of.js ***!
  \*******************************************************************/function(e,n,o){var s=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),t=o(/*! ../internals/an-object */"./node_modules/core-js/internals/an-object.js"),i=o(/*! ../internals/a-possible-prototype */"./node_modules/core-js/internals/a-possible-prototype.js");e.exports=Object.setPrototypeOf||("__proto__"in{}?function(){var o,r=!1,e={};try{(o=s(Object.getOwnPropertyDescriptor(Object.prototype,"__proto__").set))(e,[]),r=e instanceof Array}catch(e){}return function(e,n){return t(e),i(n),r?o(e,n):e.__proto__=n,e}}():void 0)},"./node_modules/core-js/internals/object-to-string.js":
/*!************************************************************!*\
  !*** ./node_modules/core-js/internals/object-to-string.js ***!
  \************************************************************/function(e,n,o){"use strict";var r=o(/*! ../internals/to-string-tag-support */"./node_modules/core-js/internals/to-string-tag-support.js"),s=o(/*! ../internals/classof */"./node_modules/core-js/internals/classof.js");e.exports=r?{}.toString:function(){return"[object "+s(this)+"]"}},"./node_modules/core-js/internals/ordinary-to-primitive.js":
/*!*****************************************************************!*\
  !*** ./node_modules/core-js/internals/ordinary-to-primitive.js ***!
  \*****************************************************************/function(e,n,o){var s=o(/*! ../internals/function-call */"./node_modules/core-js/internals/function-call.js"),t=o(/*! ../internals/is-callable */"./node_modules/core-js/internals/is-callable.js"),i=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),c=TypeError;e.exports=function(e,n){var o,r;if("string"===n&&t(o=e.toString)&&!i(r=s(o,e)))return r;if(t(o=e.valueOf)&&!i(r=s(o,e)))return r;if("string"!==n&&t(o=e.toString)&&!i(r=s(o,e)))return r;throw c("Can't convert object to primitive value")}},"./node_modules/core-js/internals/own-keys.js":
/*!****************************************************!*\
  !*** ./node_modules/core-js/internals/own-keys.js ***!
  \****************************************************/function(e,n,o){var r=o(/*! ../internals/get-built-in */"./node_modules/core-js/internals/get-built-in.js"),s=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),t=o(/*! ../internals/object-get-own-property-names */"./node_modules/core-js/internals/object-get-own-property-names.js"),i=o(/*! ../internals/object-get-own-property-symbols */"./node_modules/core-js/internals/object-get-own-property-symbols.js"),c=o(/*! ../internals/an-object */"./node_modules/core-js/internals/an-object.js"),l=s([].concat);e.exports=r("Reflect","ownKeys")||function(e){var n=t.f(c(e)),o=i.f;return o?l(n,o(e)):n}},"./node_modules/core-js/internals/require-object-coercible.js":
/*!********************************************************************!*\
  !*** ./node_modules/core-js/internals/require-object-coercible.js ***!
  \********************************************************************/function(e){var n=TypeError;e.exports=function(e){if(null==e)throw n("Can't call method on "+e);return e}},"./node_modules/core-js/internals/shared-key.js":
/*!******************************************************!*\
  !*** ./node_modules/core-js/internals/shared-key.js ***!
  \******************************************************/function(e,n,o){var r=o(/*! ../internals/shared */"./node_modules/core-js/internals/shared.js"),s=o(/*! ../internals/uid */"./node_modules/core-js/internals/uid.js"),t=r("keys");e.exports=function(e){return t[e]||(t[e]=s(e))}},"./node_modules/core-js/internals/shared-store.js":
/*!********************************************************!*\
  !*** ./node_modules/core-js/internals/shared-store.js ***!
  \********************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),o=o(/*! ../internals/define-global-property */"./node_modules/core-js/internals/define-global-property.js"),s="__core-js_shared__",r=r[s]||o(s,{});e.exports=r},"./node_modules/core-js/internals/shared.js":
/*!**************************************************!*\
  !*** ./node_modules/core-js/internals/shared.js ***!
  \**************************************************/function(e,n,o){var r=o(/*! ../internals/is-pure */"./node_modules/core-js/internals/is-pure.js"),s=o(/*! ../internals/shared-store */"./node_modules/core-js/internals/shared-store.js");(e.exports=function(e,n){return s[e]||(s[e]=void 0!==n?n:{})})("versions",[]).push({version:"3.24.0",mode:r?"pure":"global",copyright:"© 2014-2022 Denis Pushkarev (zloirock.ru)",license:"https://github.com/zloirock/core-js/blob/v3.24.0/LICENSE",source:"https://github.com/zloirock/core-js"})},"./node_modules/core-js/internals/string-trim.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/string-trim.js ***!
  \*******************************************************/function(e,n,o){function r(n){return function(e){e=i(t(e));return 1&n&&(e=c(e,l,"")),e=2&n?c(e,u,""):e}}var s=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),t=o(/*! ../internals/require-object-coercible */"./node_modules/core-js/internals/require-object-coercible.js"),i=o(/*! ../internals/to-string */"./node_modules/core-js/internals/to-string.js"),o=o(/*! ../internals/whitespaces */"./node_modules/core-js/internals/whitespaces.js"),c=s("".replace),s="["+o+"]",l=RegExp("^"+s+s+"*"),u=RegExp(s+s+"*$");e.exports={start:r(1),end:r(2),trim:r(3)}},"./node_modules/core-js/internals/this-number-value.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/this-number-value.js ***!
  \*************************************************************/function(e,n,o){o=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js");e.exports=o(1..valueOf)},"./node_modules/core-js/internals/to-absolute-index.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/to-absolute-index.js ***!
  \*************************************************************/function(e,n,o){var r=o(/*! ../internals/to-integer-or-infinity */"./node_modules/core-js/internals/to-integer-or-infinity.js"),s=Math.max,t=Math.min;e.exports=function(e,n){e=r(e);return e<0?s(e+n,0):t(e,n)}},"./node_modules/core-js/internals/to-indexed-object.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/to-indexed-object.js ***!
  \*************************************************************/function(e,n,o){var r=o(/*! ../internals/indexed-object */"./node_modules/core-js/internals/indexed-object.js"),s=o(/*! ../internals/require-object-coercible */"./node_modules/core-js/internals/require-object-coercible.js");e.exports=function(e){return r(s(e))}},"./node_modules/core-js/internals/to-integer-or-infinity.js":
/*!******************************************************************!*\
  !*** ./node_modules/core-js/internals/to-integer-or-infinity.js ***!
  \******************************************************************/function(e,n,o){var r=o(/*! ../internals/math-trunc */"./node_modules/core-js/internals/math-trunc.js");e.exports=function(e){e=+e;return e!=e||0==e?0:r(e)}},"./node_modules/core-js/internals/to-length.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/to-length.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/to-integer-or-infinity */"./node_modules/core-js/internals/to-integer-or-infinity.js"),s=Math.min;e.exports=function(e){return 0<e?s(r(e),9007199254740991):0}},"./node_modules/core-js/internals/to-object.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/to-object.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/require-object-coercible */"./node_modules/core-js/internals/require-object-coercible.js"),s=Object;e.exports=function(e){return s(r(e))}},"./node_modules/core-js/internals/to-primitive.js":
/*!********************************************************!*\
  !*** ./node_modules/core-js/internals/to-primitive.js ***!
  \********************************************************/function(e,n,o){var r=o(/*! ../internals/function-call */"./node_modules/core-js/internals/function-call.js"),s=o(/*! ../internals/is-object */"./node_modules/core-js/internals/is-object.js"),t=o(/*! ../internals/is-symbol */"./node_modules/core-js/internals/is-symbol.js"),i=o(/*! ../internals/get-method */"./node_modules/core-js/internals/get-method.js"),c=o(/*! ../internals/ordinary-to-primitive */"./node_modules/core-js/internals/ordinary-to-primitive.js"),o=o(/*! ../internals/well-known-symbol */"./node_modules/core-js/internals/well-known-symbol.js"),l=TypeError,u=o("toPrimitive");e.exports=function(e,n){if(!s(e)||t(e))return e;var o=i(e,u);if(o){if(o=r(o,e,n=void 0===n?"default":n),!s(o)||t(o))return o;throw l("Can't convert object to primitive value")}return c(e,n=void 0===n?"number":n)}},"./node_modules/core-js/internals/to-property-key.js":
/*!***********************************************************!*\
  !*** ./node_modules/core-js/internals/to-property-key.js ***!
  \***********************************************************/function(e,n,o){var r=o(/*! ../internals/to-primitive */"./node_modules/core-js/internals/to-primitive.js"),s=o(/*! ../internals/is-symbol */"./node_modules/core-js/internals/is-symbol.js");e.exports=function(e){e=r(e,"string");return s(e)?e:e+""}},"./node_modules/core-js/internals/to-string-tag-support.js":
/*!*****************************************************************!*\
  !*** ./node_modules/core-js/internals/to-string-tag-support.js ***!
  \*****************************************************************/function(e,n,o){var r={};r[o(/*! ../internals/well-known-symbol */"./node_modules/core-js/internals/well-known-symbol.js")("toStringTag")]="z",e.exports="[object z]"===String(r)},"./node_modules/core-js/internals/to-string.js":
/*!*****************************************************!*\
  !*** ./node_modules/core-js/internals/to-string.js ***!
  \*****************************************************/function(e,n,o){var r=o(/*! ../internals/classof */"./node_modules/core-js/internals/classof.js"),s=String;e.exports=function(e){if("Symbol"===r(e))throw TypeError("Cannot convert a Symbol value to a string");return s(e)}},"./node_modules/core-js/internals/try-to-string.js":
/*!*********************************************************!*\
  !*** ./node_modules/core-js/internals/try-to-string.js ***!
  \*********************************************************/function(e){var n=String;e.exports=function(e){try{return n(e)}catch(e){return"Object"}}},"./node_modules/core-js/internals/uid.js":
/*!***********************************************!*\
  !*** ./node_modules/core-js/internals/uid.js ***!
  \***********************************************/function(e,n,o){var o=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),r=0,s=Math.random(),t=o(1..toString);e.exports=function(e){return"Symbol("+(void 0===e?"":e)+")_"+t(++r+s,36)}},"./node_modules/core-js/internals/use-symbol-as-uid.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/use-symbol-as-uid.js ***!
  \*************************************************************/function(e,n,o){o=o(/*! ../internals/native-symbol */"./node_modules/core-js/internals/native-symbol.js");e.exports=o&&!Symbol.sham&&"symbol"==typeof Symbol.iterator},"./node_modules/core-js/internals/v8-prototype-define-bug.js":
/*!*******************************************************************!*\
  !*** ./node_modules/core-js/internals/v8-prototype-define-bug.js ***!
  \*******************************************************************/function(e,n,o){var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),o=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js");e.exports=r&&o(function(){return 42!=Object.defineProperty(function(){},"prototype",{value:42,writable:!1}).prototype})},"./node_modules/core-js/internals/well-known-symbol.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/internals/well-known-symbol.js ***!
  \*************************************************************/function(e,n,o){var r=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),s=o(/*! ../internals/shared */"./node_modules/core-js/internals/shared.js"),t=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),i=o(/*! ../internals/uid */"./node_modules/core-js/internals/uid.js"),c=o(/*! ../internals/native-symbol */"./node_modules/core-js/internals/native-symbol.js"),l=o(/*! ../internals/use-symbol-as-uid */"./node_modules/core-js/internals/use-symbol-as-uid.js"),u=s("wks"),a=r.Symbol,d=a&&a.for,j=l?a:a&&a.withoutSetter||i;e.exports=function(e){var n;return t(u,e)&&(c||"string"==typeof u[e])||(n="Symbol."+e,c&&t(a,e)?u[e]=a[e]:u[e]=(l&&d?d:j)(n)),u[e]}},"./node_modules/core-js/internals/whitespaces.js":
/*!*******************************************************!*\
  !*** ./node_modules/core-js/internals/whitespaces.js ***!
  \*******************************************************/function(e){e.exports="\t\n\v\f\r                　\u2028\u2029\ufeff"},"./node_modules/core-js/modules/es.array.for-each.js":
/*!***********************************************************!*\
  !*** ./node_modules/core-js/modules/es.array.for-each.js ***!
  \***********************************************************/function(e,n,o){"use strict";var r=o(/*! ../internals/export */"./node_modules/core-js/internals/export.js"),o=o(/*! ../internals/array-for-each */"./node_modules/core-js/internals/array-for-each.js");r({target:"Array",proto:!0,forced:[].forEach!=o},{forEach:o})},"./node_modules/core-js/modules/es.number.constructor.js":
/*!***************************************************************!*\
  !*** ./node_modules/core-js/modules/es.number.constructor.js ***!
  \***************************************************************/function(e,n,o){"use strict";var r=o(/*! ../internals/descriptors */"./node_modules/core-js/internals/descriptors.js"),s=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),t=o(/*! ../internals/function-uncurry-this */"./node_modules/core-js/internals/function-uncurry-this.js"),i=o(/*! ../internals/is-forced */"./node_modules/core-js/internals/is-forced.js"),c=o(/*! ../internals/define-built-in */"./node_modules/core-js/internals/define-built-in.js"),l=o(/*! ../internals/has-own-property */"./node_modules/core-js/internals/has-own-property.js"),u=o(/*! ../internals/inherit-if-required */"./node_modules/core-js/internals/inherit-if-required.js"),a=o(/*! ../internals/object-is-prototype-of */"./node_modules/core-js/internals/object-is-prototype-of.js"),d=o(/*! ../internals/is-symbol */"./node_modules/core-js/internals/is-symbol.js"),j=o(/*! ../internals/to-primitive */"./node_modules/core-js/internals/to-primitive.js"),f=o(/*! ../internals/fails */"./node_modules/core-js/internals/fails.js"),m=o(/*! ../internals/object-get-own-property-names */"./node_modules/core-js/internals/object-get-own-property-names.js").f,_=o(/*! ../internals/object-get-own-property-descriptor */"./node_modules/core-js/internals/object-get-own-property-descriptor.js").f,p=o(/*! ../internals/object-define-property */"./node_modules/core-js/internals/object-define-property.js").f,b=o(/*! ../internals/this-number-value */"./node_modules/core-js/internals/this-number-value.js"),y=o(/*! ../internals/string-trim */"./node_modules/core-js/internals/string-trim.js").trim,o="Number",h=s[o],v=h.prototype,g=s.TypeError,S=t("".slice),E=t("".charCodeAt),T=function(e){var n,o,r,s,t,i,c,l=j(e,"number");if(d(l))throw g("Cannot convert a Symbol value to a number");if("string"==typeof l&&2<l.length)if(l=y(l),43===(e=E(l,0))||45===e){if(88===(n=E(l,2))||120===n)return NaN}else if(48===e){switch(E(l,1)){case 66:case 98:o=2,r=49;break;case 79:case 111:o=8,r=55;break;default:return+l}for(t=(s=S(l,2)).length,i=0;i<t;i++)if((c=E(s,i))<48||r<c)return NaN;return parseInt(s,o)}return+l};if(i(o,!h(" 0o1")||!h("0b1")||h("+0x1"))){for(var I,x=function(e){var e=arguments.length<1?0:h(function(e){e=j(e,"number");return"bigint"==typeof e?e:T(e)}(e)),n=this;return a(v,n)&&f(function(){b(n)})?u(Object(e),n,x):e},L=r?m(h):"MAX_VALUE,MIN_VALUE,NaN,NEGATIVE_INFINITY,POSITIVE_INFINITY,EPSILON,MAX_SAFE_INTEGER,MIN_SAFE_INTEGER,isFinite,isInteger,isNaN,isSafeInteger,parseFloat,parseInt,fromString,range".split(","),w=0;L.length>w;w++)l(h,I=L[w])&&!l(x,I)&&p(x,I,_(h,I));c(s,o,(x.prototype=v).constructor=x,{constructor:!0})}},"./node_modules/core-js/modules/es.object.to-string.js":
/*!*************************************************************!*\
  !*** ./node_modules/core-js/modules/es.object.to-string.js ***!
  \*************************************************************/function(e,n,o){var r=o(/*! ../internals/to-string-tag-support */"./node_modules/core-js/internals/to-string-tag-support.js"),s=o(/*! ../internals/define-built-in */"./node_modules/core-js/internals/define-built-in.js"),o=o(/*! ../internals/object-to-string */"./node_modules/core-js/internals/object-to-string.js");r||s(Object.prototype,"toString",o,{unsafe:!0})},"./node_modules/core-js/modules/web.dom-collections.for-each.js":
/*!**********************************************************************!*\
  !*** ./node_modules/core-js/modules/web.dom-collections.for-each.js ***!
  \**********************************************************************/function(e,n,o){function r(n){if(n&&n.forEach!==l)try{u(n,"forEach",l)}catch(e){n.forEach=l}}var s,t=o(/*! ../internals/global */"./node_modules/core-js/internals/global.js"),i=o(/*! ../internals/dom-iterables */"./node_modules/core-js/internals/dom-iterables.js"),c=o(/*! ../internals/dom-token-list-prototype */"./node_modules/core-js/internals/dom-token-list-prototype.js"),l=o(/*! ../internals/array-for-each */"./node_modules/core-js/internals/array-for-each.js"),u=o(/*! ../internals/create-non-enumerable-property */"./node_modules/core-js/internals/create-non-enumerable-property.js");for(s in i)i[s]&&r(t[s]&&t[s].prototype);r(c)}},r={};function _(e){var n=r[e];if(void 0!==n)return n.exports;n=r[e]={exports:{}};return o[e](n,n.exports,_),n.exports}_.n=function(e){var n=e&&e.__esModule?function(){return e.default}:function(){return e};return _.d(n,{a:n}),n},_.d=function(e,n){for(var o in n)_.o(n,o)&&!_.o(e,o)&&Object.defineProperty(e,o,{enumerable:!0,get:n[o]})},_.g=function(){if("object"==typeof globalThis)return globalThis;try{return this||new Function("return this")()}catch(e){if("object"==typeof window)return window}}(),_.o=function(e,n){return Object.prototype.hasOwnProperty.call(e,n)},_.r=function(e){"undefined"!=typeof Symbol&&Symbol.toStringTag&&Object.defineProperty(e,Symbol.toStringTag,{value:"Module"}),Object.defineProperty(e,"__esModule",{value:!0})};var p={};!function(){"use strict";
/*!******************************************!*\
  !*** ./source/scripts/project-slider.js ***!
  \******************************************/_.r(p);_(/*! core-js/modules/es.number.constructor.js */"./node_modules/core-js/modules/es.number.constructor.js"),_(/*! core-js/modules/es.array.for-each.js */"./node_modules/core-js/modules/es.array.for-each.js"),_(/*! core-js/modules/es.object.to-string.js */"./node_modules/core-js/modules/es.object.to-string.js"),_(/*! core-js/modules/web.dom-collections.for-each.js */"./node_modules/core-js/modules/web.dom-collections.for-each.js");var e,n,o,r,s,t,i,c,l,u=_(/*! ./consts */"./source/scripts/consts.js");function a(){+this.getAttribute(u.SLIDER_DATA_ATTRIBUTE)>r&&(t=u.SWIP_DIRRECTION.RIGHT),+this.getAttribute(u.SLIDER_DATA_ATTRIBUTE)<r&&(t=u.SWIP_DIRRECTION.LEFT),s=Number(r),r=Number(this.getAttribute(u.SLIDER_DATA_ATTRIBUTE)),d(),j(),f()}function d(){o.forEach(function(e){e.classList.remove(u.SLIDER_HIDDEN_SLIDE_LEFT),e.classList.remove(u.SLIDER_HIDDEN_SLIDE_RIGHT),+e.getAttribute(u.SLIDER_DATA_ATTRIBUTE)==+s&&e.classList.add("project-slider__slide--hidden--".concat(t))})}function j(){n.forEach(function(e){Number(e.getAttribute(u.SLIDER_DATA_ATTRIBUTE))===Number(r)?e.classList.add(u.SLIDER_ACTIVE_BUTTON_CLASS):e.classList.remove(u.SLIDER_ACTIVE_BUTTON_CLASS)})}function f(){o.forEach(function(e){e.classList.remove(u.SLIDER_ACTIVE_SLIDE_LEFT),e.classList.remove(u.SLIDER_ACTIVE_SLIDE_RIGHT),Number(e.getAttribute(u.SLIDER_DATA_ATTRIBUTE))===Number(r)&&e.classList.add("project-slider__slide--active--".concat(t))})}function m(){var e;e={x:i.x-c.x,y:i.y-c.y},Math.abs(e.x)>Math.abs(e.y)&&Math.abs(e.x)>l&&(0<e.x?(t=u.SWIP_DIRRECTION.RIGHT,Number(r)===o.length?r=Number(n[0].getAttribute(u.SLIDER_DATA_ATTRIBUTE)):r++):(t=u.SWIP_DIRRECTION.LEFT,1===Number(r)?r=o.length:r--),t===u.SWIP_DIRRECTION.RIGHT&&(s=1===Number(r)?n.length:Number(r)-1),t===u.SWIP_DIRRECTION.LEFT&&(s=Number(r)===n.length?1:Number(r)+1),d(),j(),f()),c=i=null}e=document.querySelector(".project-slider__slides"),n=document.querySelectorAll(".project-slider__thumbnails-button"),o=document.querySelectorAll(".project-slider__slide"),r=Number(n[0].getAttribute(u.SLIDER_DATA_ATTRIBUTE)),s=+n[n.length-1].getAttribute(u.SLIDER_DATA_ATTRIBUTE),t=u.SWIP_DIRRECTION.RIGHT,f(),j(),n.forEach(function(e){e.addEventListener("click",a,{passive:!0})}),c=i=null,l=20,e.addEventListener("touchstart",function(e){i={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY},c={x:i.x,y:i.y}},{passive:!0}),e.addEventListener("touchmove",function(e){c={x:e.changedTouches[0].clientX,y:e.changedTouches[0].clientY}},{passive:!0}),e.addEventListener("touchend",function(e){m()},{passive:!0}),e.addEventListener("touchcancel",function(e){m()},{passive:!0})}()}();
//# sourceMappingURL=project-slider.js.map